import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import { ITrip } from '../models/Trip.model'

/**
 * Generate a PDF Itinerary for a given Trip
 * Returns a Buffer that can be sent to the client
 */
export const generateTripPdf = async (trip: ITrip): Promise<Buffer> => {
  // 1. Create a new PDF document (A4 size)
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  })

  // --- Header ---
  doc.setFillColor(74, 20, 140)
  doc.rect(0, 0, 210, 40, 'F')

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(22)
  doc.text('GoLanka Travel', 105, 15, { align: 'center' })
  
  doc.setFontSize(12)
  doc.text('Your Dream Journey Awaits', 105, 25, { align: 'center' })

  // --- Trip Info ---
  doc.setTextColor(0, 0, 0)
  doc.setFontSize(16)
  doc.text(`Trip: ${trip.name}`, 14, 55)

  doc.setFontSize(11)
  doc.setTextColor(100)
  doc.text(`Destination: ${trip.destination}`, 14, 63)
  doc.text(`Duration: ${trip.duration} Days`, 14, 69)
  doc.text(`Price: ${trip.currency} ${trip.price.toLocaleString()}`, 14, 75)
  
  // Dates (if active)
  const startDate = trip.startDate ? new Date(trip.startDate).toDateString() : 'Flexible'
  doc.text(`Travel Date: ${startDate}`, 14, 81)

  // --- Itinerary Table ---
  // Prepare data for the table
  const tableRows: any[] = []
  
  if (trip.itinerary && trip.itinerary.length > 0) {
    trip.itinerary.forEach((dayPlan: any) => {
      // Create a row for the Day Summary
      tableRows.push([{ 
        content: `Day ${dayPlan.day}: ${dayPlan.theme || 'Exploration'}`, 
        colSpan: 2, 
        styles: { fillColor: [240, 240, 240], fontStyle: 'bold' } 
      }])

      // Add rows for activities
      if (dayPlan.activities) {
        dayPlan.activities.forEach((act: any) => {
          tableRows.push([
            act.time || '-',
            `${act.activity}\n${act.description || ''}`
          ])
        })
      }
    })
  }

  // Generate the AutoTable
  autoTable(doc, {
    startY: 90,
    head: [['Time', 'Activity Details']],
    body: tableRows,
    theme: 'grid',
    headStyles: { fillColor: [74, 20, 140], textColor: 255 }, 
    styles: { fontSize: 10, cellPadding: 4 },
    columnStyles: {
      0: { cellWidth: 30 }, 
      1: { cellWidth: 'auto' } 
    }
  })

  // --- Footer ---
  const pageHeight = doc.internal.pageSize.height
  doc.setFontSize(10)
  doc.setTextColor(150)
  doc.text('Generated by GoLanka AI Planner', 14, pageHeight - 10)
  doc.text(`www.golankatravel.com`, 195, pageHeight - 10, { align: 'right' })

  // Return generated PDF as ArrayBuffer
  return Buffer.from(doc.output('arraybuffer'))
}